pipeline {
    agent any 
    stages {
        stage ('pom files'){
        steps{
            sh ' pwd'
        }
    }
        stage('clean') { 
            steps {
                sh 'mvn clean'
            }
        }
        stage('validate') { 
            steps {
                sh 'mvn validate'
            }
        }
    }
}
