pipeline {
    agent any 
    stages {
        stage ('pom files'){
        steps{
            sh ' pwd'
            sh 'rm -r *'
            sh 'mvn clean'
        }
    }
        
    }
}
