pipeline {
    agent any 
    stages {
        stage ('pom files'){
        steps{
            sh ' pwd'
        }
    }
        stage('moving to pom'){
            steps{
         sh 'ls'      
                sh ' cd Calculator'
                sh ' ls -l'
            }
        }
    }
}
